// ─── BRACU CSE Course Dictionary ──────────────────────
// Maps course codes to their official titles.
// Sources: BRACU CSE website + department spreadsheet.

const COURSE_MAP = {
  // ─── Core / Undergraduate ──────────────────────────
  'CSE110': 'Programming Language I',
  'CSE111': 'Programming Language II',
  'CSE220': 'Data Structure',
  'CSE221': 'Algorithm Analysis & Design',
  'CSE230': 'Discrete Mathematics',
  'CSE250': 'Circuits and Electronics',
  'CSE251': 'Electronic Devices and Circuits',
  'CSE260': 'Digital Logic Design',
  'CSE310': 'Object-Oriented Programming',
  'CSE320': 'Data Communications',
  'CSE321': 'Operating Systems',
  'CSE330': 'Numerical Methods',
  'CSE331': 'Automata and Computability',
  'CSE340': 'Computer Architecture',
  'CSE341': 'Microprocessors',
  'CSE342': 'Computer System Engineering',
  'CSE350': 'Digital Electronics and Pulse Techniques',
  'CSE360': 'Computer Interfacing',
  'CSE370': 'Database',
  'CSE390': 'Technical Communication',
  'CSE391': 'Programming for the Internet',
  'CSE392': 'Signals and Systems',
  'CSE400': 'Final Year Design Project',
  'CSE402': 'Optimization',
  'CSE410': 'Advanced Programming in UNIX',
  'CSE419': 'Programming Languages and Competitive Programming',
  'CSE420': 'Compiler Design',
  'CSE421': 'Computer Networks',
  'CSE422': 'Artificial Intelligence',
  'CSE423': 'Computer Graphics',
  'CSE424': 'Pattern Recognition',
  'CSE425': 'Neural Network',
  'CSE426': 'Advanced Algorithms',
  'CSE427': 'Machine Learning',
  'CSE428': 'Image Processing',
  'CSE429': 'Basic Multimedia Theory',
  'CSE430': 'Digital Signal Processing',
  'CSE431': 'Natural Language Processing',
  'CSE432': 'Speech Recognition and Synthesis',
  'CSE433': 'Machine Learning for Healthcare',
  'CSE434': 'Machine Learning for Finance',
  'CSE435': 'Reinforcement Learning',
  'CSE437': 'Data Science: Coding With Real-World Data',
  'CSE438': 'Applied Data Science for Practitioners',
  'CSE439': 'Machine Vision',
  'CSE440': 'Natural Language Processing (NLP) II',
  'CSE441': 'Machine Learning II',
  'CSE442': 'Natural Language-Driven UI/UX',
  'CSE443': 'Bioinformatics I',
  'CSE444': 'Bioinformatics II',
  'CSE445': 'Statistical Data Analysis',
  'CSE446': 'Blockchain and Cryptocurrencies',
  'CSE447': 'Cryptography and Cryptoanalysis',
  'CSE449': 'Parallel, Distributed and High-Performance Computing',
  'CSE450': 'Advanced Competitive Programming',
  'CSE451': 'Network Science and Models',
  'CSE452': 'Computability and Complexity Theory',
  'CSE453': 'Theory of Computation II',
  'CSE454': 'Advanced Complexity Theory',
  'CSE455': 'Topics in Theoretical Computer Science',
  'CSE456': 'Design and Analysis of Algorithms',
  'CSE457': 'Randomized Algorithms',
  'CSE458': 'Quantum Complexity Theory',
  'CSE459': 'Introduction to Computational Molecular Biology',
  'CSE460': 'VLSI Design',
  'CSE461': 'Introduction to Robotics',
  'CSE462': 'Fault Tolerance System',
  'CSE463': 'Computer Vision: Fundamentals and Applications',
  'CSE470': 'Software Engineering',
  'CSE471': 'System Analysis and Design',
  'CSE472': 'Human Computer Interface',
  'CSE473': 'Financial Engineering & Technology',
  'CSE474': 'Simulation and Modeling',
  'CSE481': 'Quantum Computing I',
  'CSE482': 'Quantum Computing II',
  'CSE483': 'Software Engineering II',
  'CSE484': 'Cloud Computing',
  'CSE485': 'Advanced Cloud Computing',
  'CSE486': 'LAN Switching and WAN Technologies',
  'CSE487': 'Web Services',
  'CSE488': 'Serverless and Microservices',
  'CSE489': 'Android App Development',
  'CSE490A': 'Gamification: Engineering User Engagement',
  'CSE490B': 'Introduction to Cybersecurity',
  'CSE490C': 'Quantum Computing III',
  'CSE490D': 'Introduction to Football Data and Analytics',
  'CSE492': 'iOS App Development',
  'CSE493': 'Enterprise and Software Architecture',
  'CSE494': 'Advanced Robotics',
  'CSE495': 'Internet of Things (IoT)',
  'CSE496': 'Ethical Hacking',
  'CSE497': 'Computational Cognitive Science',
  'CSE498': 'Advanced Graphics',
  'CSE499': 'E-commerce',
  'CSE500': 'Ethics of Data in Social Context',
  'CSE502': 'Scientific and Engineering Innovation',
  'CSE503': 'Project Engineering for Computer Science',
  'CSE504': 'Workshop for Entrepreneurs and Innovators',
  'CSE505': 'Patents, Copyrights, and IP Law',
  'CSE506': 'Ethics for Engineers and Scientists',
  'CSE507': 'Introduction to Design Thinking and Innovation',
  'CSE586': 'Advanced Web Development',

  // ─── Postgraduate ──────────────────────────────────
  'CSE700': 'Thesis',
  'CSE705': 'Computer Communications and Networks',
  'CSE706': 'Advanced Parallel Algorithm',
  'CSE707': 'Distributed Computing Systems',
  'CSE708': 'Graph Theory',
  'CSE709': 'Computational Geometry',
  'CSE710': 'Advanced Artificial Intelligence',
  'CSE711': 'Advanced Machine Learning',
  'CSE713': 'Advanced Syntactic Pattern Recognition',
  'CSE715': 'Neural Networks and Fuzzy System',
  'CSE716': 'Advanced Database Systems',
  'CSE717': 'Mathematical Programming',
  'CSE718': 'Petri-Net Theory and System Modeling',
  'CSE720': 'Computer Graphics and Animation',
  'CSE721': 'Introduction to Cryptography',
  'CSE722': 'Applied Cryptography and Cryptographic Protocols',
  'CSE723': 'Web Security',
  'CSE724': 'Ethical Hacking',
  'CSE725': 'Cybersecurity Policy and Risk Management',
  'CSE726': 'Information Assurance',
  'CSE727': 'Digital Forensics',
  'CSE728': 'Privacy Enhancing Technologies',
  'CSE729': 'Blockchain and Distributed Ledger',
  'CSE730': 'Threat Intelligence and Incident Response',
  'CSE731': 'HCI and Design',
  'CSE732': 'Advanced Quantum Computing',
  'CSE741': 'Advanced Cloud Computing',
  'CSE751': 'Advanced Natural Language Processing',
  'CSE752': 'Deep Neural Networks',
  'CSE753': 'Advanced Reinforcement Learning',
  'CSE754': 'Deep Learning for Computer Vision',
  'CSE755': 'Generative Machine Learning',
  'CSE756': 'Probabilistic Graphical Models',
  'CSE757': 'Machine Learning Systems Design',
  'CSE758': 'Data Mining',
  'CSE759': 'AI in Healthcare and Medicine',
  'CSE761': 'Big Data Analytics',
  'CSE762': 'Fairness, Ethics, and Explainability in AI',
  'CSE763': 'Advanced Bioinformatics',
  'CSE771': 'Economics of Cybersecurity',
  'CSE772': 'Secure Programming',
  'CSE773': 'Usable Security and Privacy',
  'CSE774': 'Malware Analysis',
  'CSE791': 'Research Methodology and Seminar',
  'CSE798': 'Project',

  // ─── Common Non-CSE Courses ────────────────────────
  'MAT110': 'Mathematics I: Differential Calculus & Coordinate Geometry',
  'MAT120': 'Mathematics II: Integral Calculus & Differential Equations',
  'MAT215': 'Mathematics III: Complex Variables & Laplace Transforms',
  'MAT216': 'Mathematics IV: Linear Algebra & Fourier Analysis',
  'PHY111': 'Physics I: Principles of Physics I',
  'PHY112': 'Physics II: Principles of Physics II',
  'ENG101': 'English Fundamentals',
  'ENG102': 'English Composition and Communication Skills',
  'STA201': 'Statistics for Science and Engineering',
};

/**
 * Look up a course title by its code.
 * Returns the title string or null if not found.
 */
export function getCourseTitleByCode(code) {
  if (!code) return null;
  const normalized = code.toUpperCase().trim();
  return COURSE_MAP[normalized] || null;
}

/**
 * Get the full course dictionary (for autocomplete, etc.)
 */
export function getAllCourses() {
  return COURSE_MAP;
}

export default COURSE_MAP;
